title:            Alex's Workplace
description:      Hello guys, this is my personal blog and playground
baseurl:          "" # the subpath of your site, e.g. /blog
url:              "https://alex2006-kor.github.io"

# Author
author-name:      Alex2006
author-image:     common/face_alex.jpg
author-job:       Software Engineer/Architect
author-email:     ys88.lee@gmail.com
author-twitter:   
author-about:     Hello everybody My name is Alex :)

# Social settings
social-twitter:
social-facebook:
social-github:    alex2006-kor
social-pinterest:
social-instagram:
social-youtube:
social-vk:
social-linkedin:  alex2006

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1

# Comment Section (Disqus)
discus_identifier: alexs-blog-8

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate

paginate: 8
paginate_path: "/page/:num/"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
